### ISSUE TITLE
Add new violations for Java 13-15

### ISSUE THREAD

**Issue by gaul** [gaul/modernizer-maven-plugin#115]
Audit Java 13-15 API additions using something like:

https://gunnarmorling.github.io/jdk-api-diff/jdk14-jdk15-api-diff.html

**Comment by krzyk** [comment]
I took a quick look at diffs since JDK 11 and the only obvious thing that I found was HexFormat.

Just an idea, because I don't have such live/production code to check it right now so no PR right now (until I find live use case)

It is in 17 (few days too early I know) there is a new class (https://download.java.net/java/early_access/jdk17/docs/api/java.base/java/util/HexFormat.html ) that might be useful as a replacement of:
- https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Hex.html
- https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/io/BaseEncoding.html#base16()


BTW. You can look at diffs between JDKs here: https://krzyk.github.io/jdk-api-diff-set/ (I used https://github.com/AdoptOpenJDK/jdk-api-diff to generate it) - it is not the best format but usable.

**Comment by gaul** [comment]
@krzyk @Stephan202 Could one of you look into this?  I plan to run a new release soon.

**Comment by Stephan202** [comment]
@gaul I can add this one on my TODO list, but my weekends are rather full currently. So it's hard to firmly commit at the moment. Let's see :crossed_fingers:

NB: in addition to the resources mentioned above [this website](https://javaalmanac.io/) might also be helpful :)

**Comment by gaul** [comment]
Any help on this?  I want to run another release over the holidays.

**Comment by Stephan202** [comment]
I see this one sunk down way too far on my TODO list, out of sight :(. The coming weeks are very busy, so I can't commit. (But I did just share this thread in the company Slack; maybe somebody bites :eyes: .)
