### ISSUE TITLE
Groovy fails on Java 24

### ISSUE THREAD

**Issue by mkarg** [gaul/modernizer-maven-plugin#296]
# How to reproduce?

```bash
sdk install java 24-EA-25-open
mvn verify
```

# What will go wrong?

```
[INFO] --- invoker:3.7.0:integration-test (integration-test) @ modernizer-maven-plugin ---
[INFO] Building: issue-28-option-disabled/pom.xml
[INFO] run post-build script verify.groovy
[INFO]   BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 68
[INFO]           issue-28-option-disabled/pom.xml ................. FAILED (7.562 s)
[INFO] Building: issue-28-option-enabled/pom.xml
[INFO]           issue-28-option-enabled/pom.xml .................. SUCCESS (4.360 s)
```

**Comment by gaul** [comment]
Modernizer relies on asm so I think we need to wait for a new version for this support.

**Comment by mkarg** [comment]
> Modernizer relies on asm so I think we need to wait for a new version for this support.

Modernizer already uses ASM 9.7.1 which (according to [the ASM homepage](https://asm.ow2.io/versions.html)) already supports Java 24.

**Comment by gaul** [comment]
Sorry I misunderstood earlier.  It looks like modernizer works for Java 24 but the integration tests fail due to the integration test dependency on Groovy.  I wouldn't say that Modernizer uses Groovy for the best of all possible reasons but let's wait to see what happens with version 5.0.0.  The pre-release notes claim compatibility with Java 23 via [GROOVY-11347](https://issues.apache.org/jira/browse/GROOVY-11347) so hopefully they have Java 24 soon:

https://groovy-lang.org/changelogs/changelog-5.0.0-unreleased.html

**Comment by mkarg** [comment]
I confirm that the problem is gone. `mvn clean test` now works well for me on JDK 25 EA build 29.
