### ISSUE TITLE
Prefer ThreadLocalRandom over Random in JDK>=1.7

### ISSUE THREAD

**Issue by afrin216** [gaul/modernizer-maven-plugin#61]
Prefer ThreadLocalRandom over Random to reduce contention and overhead

https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadLocalRandom.html

**Comment by afrin216** [comment]
PR - https://github.com/gaul/modernizer-maven-plugin/pull/62

**Comment by gaul** [comment]
I have concerns about a blanket recommendation for `ThreadLocalRandom` since users cannot set the seed.  Thus there is no ability to have repeatable pseudo-random numbers.

**Comment by afrin216** [comment]
Ah, I didn't think about that. This class was created by Java to reduce thread contention and synchronization blocking of `Random` class. One way that was mitigated was by internalizing the seed creation. From the numbers I've seen, I think it is beneficial that users be forced to use this class over `Random` and ignore this plugin for cases where they need repeateable random numbers (though that's not really the intention of random, is it)?

Go ahead and close this issue and PR, if community is against this rule.

**Comment by gaul** [comment]
Let's leave this open for some time to see if a consensus emerges.  I worry about the blanket recommendation since modernizer has a low false-positive rate compare to more general and powerful static analysis tools.  modernizer also lacks a suppression mechanism #3 so false-positives are more irritating than other tools.  We do have a mechanism to allow multiple and custom violation files so we could keep a second file which has less certain violations that default off?

**Comment by afrin216** [comment]
Agreed! A low priority/good practices violations file sounds like a good place for this rule. We can document that this can be used by consumers wishing to enforce extra/good practices constraints

**Comment by gaul** [comment]
Closing this due to concerns about setting the seed.
